name: Ejecutar prueba cada 5 minutos

permissions:
  contents: write

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rama prueba
        uses: actions/checkout@v4
        with:
          ref: prueba

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar script
        run: python prueba.py

      - name: Commit y push del JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output.json
          git commit -m "Actualización automática JSON" || echo "No hay cambios"
          git push origin prueba
